services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - transaction-service
    networks:
      - app-net

  transaction-service:
    build: ./transaction-service
    depends_on:
      - mnmngr-postgres
    networks:
      - app-net

  mnmngr-postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=JAS)F8g60KEGF)$
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge